import { authService } from '@/services/auth.service'
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const user = authService.getDataActive()
  console.log("layout", user)
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {/* <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/> */}
        <Header user={user}/>
        {children}
        <Footer />
        </body>
    </html>
  )
}
