import { authService } from '@/services/auth.service'
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { ProviderContainer } from '@/redux/ProviderContainer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    
      <html lang="en">
      
      <body className={inter.className}>
        <ProviderContainer>
          <Header />
        {children}
        <Footer />
        </ProviderContainer>
        
        </body>
    </html>
    
  )
    
    
}
