export const categorias = ["Mascotas",
    "Inmuebles disponibles",
    "Ofrezco mis servicios",
    "Ofrezco trabajo",
    "Artículos a la venta", 
    "Gigs - trabajos temporales",  
    "Busco trabajo"  ]

    export const subMascotas = [
        "Alimentos para mascotas",
"Gatos", 
"Perros",
"Peces",
"Reptiles",
"Encontrados y Perdidos",
"Todo lo demás"
    ]

    export const subInmuebles=[
        "Vendo Apartamento",
"Vendo Casa",
"Vendo Edificio",
"Vendo Finca rustica",
"Vendo Terreno",
"Rento Apartamento",
"Rento Casa",
"Rento Edificio",
"Rento Finca rustica",
"Rento Terreno",
"Pensionistas - Huespedes",
    ]
    export const servicios =[
"Taller mecanico",
"Salon de belleza - barbería",
"Masajes - Sauna",
"Programacion - Informatica",
"Contabilidad",
"Diseño",
"Ingeniería - Arquitectura",
"Fotografía - Video",
"Jardinería",
"Carpintería",
"Albañileria",
"Procuarcion legal",
"Reparación de electrodomesticos",
"Redacción", 
"Publicidad - Marketing",
"Tutorias",
"Entrenadores personales",
"Filmaciones - Video - Podcast",
"Limpieza",
"Guardería",
"Cuidado de mascotas",
"Otros"
    ]
    export const trabajo = [
        "Administrativo - Secretarial- Contabilidad",
"Asesores de Ventas",
"Asesoría Legal",
"Arquitectura - Ingenieria",
"Diseño",
"Telecomunicaciones - IT",
"Multimedia",
"Atencion al Publico - Call Center",
"Banca - Seguros - Consultoria",
"Legal - Procuración",
"Logistica - Distribución",
"Turismo - Hotelería",
"Comida - Restaurantes",
"Educacion - Entrenamiento",
"Marketing - Redes sociales", 
"Limpieza - Domestico",
"Cuidado de personas - mascotas",
"Pilotos",
"Salud - Belleza - Cuidado personal", 
"Construcción - Industria",
"Agricultura",
"Veterinaria",
"Mano de obra calificada",
"Eventos"
    ]
    export const venta =[
"Antiguedades",
"Artesanias",
"Computadoras",
"Electronicos",
"Telefonos",
"Electrodomésticos",
"Juguetes",
"Vehiculos",
"Motos",
"Bicicletas",
"Ropa - Calzado",
"Audio y sonido",
"Preparación de alimentos",
"Embarcaciones",
"Decoración",
"Deportes",
"Materiales",
"Telas - Costura",
"Diseño",
"Instrumentos - Music"
    ]
    export const gigs =[
"Programación",
"Creativos - Diseño",
"Reparaciones en el hogar",
"Ayuda - Domesticos",
"Eventos",
"Construcción - Reparación",
"Impresión",
"Fotografía - Video",
"Motos",
"Bicicletas",
"Ropa - Calzado",
"Audio y sonido",
"Preparación de alimentos",
"Embarcaciones"
    ]
    export const searchTrabajo =[
"Programación",
"Diseño",
"Mecanica",
"Cocina - Domesticos",
"Educación - Enseñanza",
"Construcción - Reparación",
"Contabilidad",
"Ventas",
"Secretarial - Administracion",
"Gerencia",
"Legal - Procuracion",
"Belleza - Manicure - Pedicure",
"Marketing - Multimedia",
"Profesionales"
    ]