export const departamentos = ['Alta Verapaz',
'Baja Verapaz',
'Chimaltenango',
'Chiquimula',
'El Progreso',
'Escuintla',
'Guatemala',
'Huehuetenango',
'Izabal',
'Jalapa',
'Jutiapa',
'Petén',
'Quetzaltenango',
'Quiché',
'Retalhuleu',
'Sacatepéquez',
'San Marcos',
'Santa Rosa',
'Solola',
'Suchitepéquez',
'Totonicapán',
'Zacapa']